from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled


def extract_video_id(url):
    """Extract video ID from YouTube URL."""
    if "v=" in url:
        return url.split("v=")[-1].split("&")[0]
    elif "youtu.be/" in url:
        return url.split("youtu.be/")[-1].split("?")[0]
    return None


def get_transcript_from_youtube(url):
    """Fetch transcript using YouTubeTranscriptApi."""
    try:
        video_id = extract_video_id(url)
        if not video_id:
            return None, "Invalid YouTube URL"

        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

        transcript = None

        # 1. Try English
        try:
            transcript = transcript_list.find_transcript(['en'])
        except:
            pass

        # 2. Try Tamil
        if transcript is None:
            try:
                transcript = transcript_list.find_transcript(['ta'])
            except:
                pass

        # 3. Try English autogenerated
        if transcript is None:
            try:
                transcript = transcript_list.find_generated_transcript(['en'])
            except:
                pass

        if transcript is None:
            return None, "No transcript available for this video."

        # Combine text
        full_text = " ".join([t["text"] for t in transcript.fetch()])
        return full_text, None

    except TranscriptsDisabled:
        return None, "This video has transcripts disabled."
    except Exception as e:
        return None, f"Error retrieving transcript: {str(e)}"


def load_transcript_from_file(file_path):
    """Load transcript from a text file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return f.read(), None
    except Exception as e:
        return None, f"Failed to load transcript: {str(e)}"


if __name__ == "__main__":
    print("Transcript module ready.")